name: Update Index File

on:
  push:
    branches: [ main ]

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate index file
      run: python gen_index.py

    - name: Commit and push index
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add index.json

        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          COMMIT_DATE=$(date -u +"%Y/%m/%d")
          git commit -m "Update $COMMIT_DATE Index [skip ci]"
          
          git push
        fi
